name: Chart build

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - develop

jobs:
  test-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@b43128a8b25298e1e7b043b78ea6613844e079b1 # v2.6.0

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs=cost-analyzer/ --charts cost-analyzer/ --validate-maintainers=false

      # - name: Helm lint
      #   working-directory: ./cost-analyzer
      #   run: helm lint

      - name: Helm template
        run: |
          helm template cost-analyzer/ -f cost-analyzer/values.yaml > full.yaml
          directory="cost-analyzer/ci/"
          for file in "$directory"/*; do
          if [ -f "$file" ]; then
              helm template cost-analyzer/ -f "$file" >> full.yaml
          fi
          done

      - name: Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: /kubeconform
          args: "-summary -output text full.yaml"


  # Installs the chart across a matrix of modern Kubernetes versions
  deploy-chart:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - name: v1.20
            version: v1.20.15
          - name: v1.21
            version: v1.21.14
          - name: v1.22
            version: v1.22.17
          - name: v1.23
            version: v1.23.17
          - name: v1.24
            version: v1.24.15
          - name: v1.25
            version: v1.25.11
          - name: v1.26
            version: v1.26.6
          - name: v1.27
            version: v1.27.3
          - name: v1.28
            version: v1.28.0
    needs: test-chart
    name: ${{ matrix.k8s-version.name }} test
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Create KinD cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          version: v0.20.0
          node_image: kindest/node:${{ matrix.k8s-version.version }}
          kubectl_version: ${{ matrix.k8s-version.version }}
  
      - name: Install Kubecost chart
        working-directory: ./cost-analyzer
        run: helm install --wait --wait-for-jobs kubecost . -n kubecost --create-namespace

      - name: Wait for ready 
        run: kubectl wait --namespace kubecost --for=condition=ready pod --selector app.kubernetes.io/name=cost-analyzer --timeout=120s

      - name: Run Helm tests 
        run: helm test -n kubecost kubecost